version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: event_ticketing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  postgres_data:
